// 训练动作库：镜像 client/src/constants/drillLibrary.ts。
// 后端 recommendation 只存 drill_id，详情走本地静态表按 id 查。

class DrillDetail {
  final String drillId;
  final String name;
  final String targetIssue;
  final String description;
  final int durationMinutes;
  final int sets;
  final int? reps;
  final List<String> steps;
  final List<String> tips;
  final String difficulty; // 入门/进阶/高级
  final List<String> equipment;

  const DrillDetail({
    required this.drillId,
    required this.name,
    required this.targetIssue,
    required this.description,
    required this.durationMinutes,
    required this.sets,
    this.reps,
    this.steps = const [],
    this.tips = const [],
    this.difficulty = '入门',
    this.equipment = const [],
  });
}

const List<DrillDetail> _drills = [
  DrillDetail(
    drillId: 'drill_towel_arm',
    name: '毛巾夹臂练习',
    targetIssue: 'casting',
    description: '修复下杆时过早释放手腕，找到"双臂和身体一起走"的感觉。',
    durationMinutes: 15,
    sets: 3,
    reps: 10,
    difficulty: '入门',
    equipment: ['小毛巾 × 1'],
    steps: [
      '取一条小毛巾，折叠后夹在双臂之间（肘关节内侧）',
      '做半挥杆练习，保持毛巾不掉落',
      '感受双臂与身体的连接感',
      '逐渐加大挥杆幅度到全挥',
      '每组 10 次挥杆，共 3 组，组间休息 30 秒',
    ],
  ),
  DrillDetail(
    drillId: 'drill_impact_bag',
    name: '击球包练习',
    targetIssue: 'casting',
    description: '强化击球位置的手腕前倾与身体连动，修正抛杆。',
    durationMinutes: 10,
    sets: 3,
    reps: 10,
    difficulty: '进阶',
    equipment: ['击球包或厚枕头'],
    steps: [
      '将击球包（或厚枕头）放在球位前方',
      '用半挥杆慢速击打，手腕保持前倾、杆头贴近身体',
      '记录手腕第一次"解锁"的感觉',
      '10 次为一组，共 3 组',
    ],
  ),
  DrillDetail(
    drillId: 'drill_half_swing',
    name: '半挥杆节奏练习',
    targetIssue: 'over_the_top',
    description: '建立"从内侧下杆"的路径感，缓解由外到内的击球问题。',
    durationMinutes: 20,
    sets: 5,
    reps: 10,
    difficulty: '入门',
    equipment: ['7 号铁 × 1'],
    steps: [
      '采用 7 号铁，站姿正常',
      '上杆只到水平位置（杆与地面平行）',
      '缓慢下杆，感受杆头从内侧进入击球区',
      '击球后跟进至同样高度',
      '每组 10 次，共 5 组，全程节奏 3:1',
    ],
  ),
  DrillDetail(
    drillId: 'drill_inside_path',
    name: '内侧下杆路径练习',
    targetIssue: 'over_the_top',
    description: '用地上放杆引导下杆路径从内侧进入，消除外上内下。',
    durationMinutes: 15,
    sets: 3,
    reps: 10,
    difficulty: '进阶',
    equipment: ['练习杆 × 1'],
    steps: [
      '在球位正后方 30cm 平行放一支练习杆',
      '上杆后刻意让下杆杆头沿练习杆内侧通过',
      '感受上半身被动、下半身主动的发力顺序',
      '每组 10 次，共 3 组',
    ],
  ),
  DrillDetail(
    drillId: 'drill_wall_butt',
    name: '臀贴墙练习',
    targetIssue: 'early_extension',
    description: '保持臀部与墙接触，避免下杆髋部前移（提前伸展 / 反向脊柱通用）。',
    durationMinutes: 10,
    sets: 3,
    reps: 10,
    difficulty: '入门',
    steps: [
      '背对墙站立，臀部轻贴墙面',
      '做上杆到下杆的镜像动作，臀部始终不离开墙',
      '感受脊柱角度在整个过程中保持不变',
      '10 次为一组，共 3 组',
    ],
  ),
  DrillDetail(
    drillId: 'drill_hip_rotation',
    name: '髋部旋转练习',
    targetIssue: 'sway_slide',
    description: '纠正侧移，建立髋部以脊柱为轴的"旋转"而非"平移"感。',
    durationMinutes: 15,
    sets: 3,
    reps: 30,
    difficulty: '入门',
    steps: [
      '双脚与肩同宽，将球杆横放在髋部前',
      '保持上身静止，缓慢左右旋转髋部',
      '感受髋部以脊柱为轴的旋转',
      '每次旋转幅度从小到大',
      '30 次为一组，共 3 组',
    ],
  ),
  DrillDetail(
    drillId: 'drill_mirror_spine',
    name: '镜前脊柱角度练习',
    targetIssue: 'loss_of_posture',
    description: '借助镜子观察整挥中脊柱角是否恒定。',
    durationMinutes: 10,
    sets: 2,
    reps: 10,
    difficulty: '入门',
    equipment: ['落地镜'],
    steps: [
      '面对落地镜做空挥',
      '观察从 setup 到 impact 脊柱前倾角的变化',
      '调整节奏直到差异 < 5°',
      '每组 10 次，共 2 组',
    ],
  ),
  DrillDetail(
    drillId: 'drill_weight_shift',
    name: '重心转移节奏练习',
    targetIssue: 'hanging_back',
    description: '通过节奏口令建立"后-前-后"的重心流，修正留身。',
    durationMinutes: 15,
    sets: 3,
    reps: 10,
    difficulty: '入门',
    steps: [
      '站姿自然，口令"后、前、收"配合上杆 / 下杆 / 收杆',
      '收杆时感受 80% 重心在前脚',
      '对镜子检查完成姿势',
      '每组 10 次，共 3 组',
    ],
  ),
  DrillDetail(
    drillId: 'drill_backswing_stop',
    name: '上杆截停练习',
    targetIssue: 'over_rotation',
    description: '防止过度转肩，控制上杆幅度。',
    durationMinutes: 10,
    sets: 3,
    reps: 10,
    difficulty: '入门',
    steps: [
      '上杆到杆接近水平就停住，保持 2 秒',
      '确认肩转约 90°，再开始下杆',
      '体会"到位就停"的节奏',
      '每组 10 次，共 3 组',
    ],
  ),
  DrillDetail(
    drillId: 'drill_shoulder_turn',
    name: '充分转肩练习',
    targetIssue: 'under_rotation',
    description: '强化上杆期充分转肩，提升力量传递。',
    durationMinutes: 10,
    sets: 3,
    reps: 20,
    difficulty: '入门',
    steps: [
      '双手交叉抱肩',
      '做上半身旋转，直到左肩触到下巴',
      '保持髋部角度基本不变',
      '20 次为一组，共 3 组',
    ],
  ),
  DrillDetail(
    drillId: 'drill_plane_board',
    name: '挥杆平面板练习',
    targetIssue: 'flat_shoulder',
    description: '借助倾斜板（或墙角）修正肩平面角。',
    durationMinutes: 15,
    sets: 3,
    reps: 10,
    difficulty: '进阶',
    equipment: ['练习板 / 厚枕头'],
    steps: [
      '在挥杆轨迹一侧斜放练习板 / 枕头',
      '上杆 / 下杆沿板面移动，既不过高也不过低',
      '感受杆头始终在肩平面上',
      '每组 10 次，共 3 组',
    ],
  ),
  DrillDetail(
    drillId: 'drill_alignment_stick',
    name: '瞄准杆站位练习',
    targetIssue: 'open_stance',
    description: '用瞄准杆纠正站位与目标线的夹角。',
    durationMinutes: 5,
    sets: 2,
    reps: 10,
    difficulty: '入门',
    equipment: ['瞄准杆 × 1'],
    steps: [
      '在球位前方 2m 放置瞄准杆指向目标',
      '双脚、双膝、肩线都与瞄准杆平行',
      '检查自身影子 / 镜子里的角度',
      '每组 10 次 setup 练习，共 2 组',
    ],
  ),
  DrillDetail(
    drillId: 'drill_grip_checkpoint',
    name: '握杆检查点练习',
    targetIssue: 'grip_weak',
    description: '按照标准握杆法复位左右手位置。',
    durationMinutes: 5,
    sets: 1,
    reps: 5,
    difficulty: '入门',
    steps: [
      '左手握杆，确认看到 2-3 颗指关节',
      '右手叠握，V 字指向右肩',
      '保持握杆压力 4/10',
      '练习 5 次，每次保持 10 秒',
    ],
  ),
  DrillDetail(
    drillId: 'drill_one_hand_putt',
    name: '单手推杆练习',
    targetIssue: 'putting_unstable_pendulum',
    description: '强化肩部钟摆主导，减少手腕独立发力。',
    durationMinutes: 15,
    sets: 3,
    difficulty: '入门',
    tips: ['握压约 3/10，避免手指单独发力', '推完停留 1 秒再抬头看球线'],
    steps: ['非主导手背后', '主导手推 10 球', '关注肩臂一体'],
  ),
  DrillDetail(
    drillId: 'drill_gate_putt',
    name: '门型推杆练习',
    targetIssue: 'putting_face_open',
    description: '用 tees 做门型，约束杆头路径与杆面方正。',
    durationMinutes: 12,
    sets: 3,
    difficulty: '入门',
    steps: ['球两侧插 tee', '推杆通过门型', '逐渐缩短门宽'],
  ),
  DrillDetail(
    drillId: 'drill_distance_ladder',
    name: '推杆距离梯',
    targetIssue: 'putting_rushed_tempo',
    description: '3/6/9 米递进，训练节奏与距离感。',
    durationMinutes: 20,
    sets: 1,
    difficulty: '进阶',
    steps: ['标记 3 个距离', '同一节奏各推 5 球', '记录落点'],
  ),
  DrillDetail(
    drillId: 'drill_eyes_closed_putt',
    name: '闭眼推杆',
    targetIssue: 'putting_head_moved',
    description: '减少视觉依赖，稳定头部与钟摆感。',
    durationMinutes: 10,
    sets: 3,
    difficulty: '入门',
    steps: ['1 米起推', '闭眼完成', '逐步加长'],
  ),
  DrillDetail(
    drillId: 'drill_chip_land_spot',
    name: '切杆落点练习',
    targetIssue: 'chipping_chunked',
    description: '先控落点再滚，建立触球前规划。',
    durationMinutes: 15,
    sets: 4,
    difficulty: '入门',
    steps: ['选落点圈', '切到落点停', '记录过/短'],
  ),
  DrillDetail(
    drillId: 'drill_low_runner',
    name: '低滚切杆',
    targetIssue: 'chipping_scoop',
    description: '杆身前倾、短幅度，练低弹道滚进。',
    durationMinutes: 12,
    sets: 3,
    difficulty: '进阶',
    steps: ['球位偏后', '杆身前倾', '短切低滚'],
  ),
  DrillDetail(
    drillId: 'drill_hinge_chip',
    name: '铰链切杆',
    targetIssue: 'chipping_decel',
    description: '上杆小铰链、下杆加速通过球。',
    durationMinutes: 15,
    sets: 3,
    difficulty: '进阶',
    steps: ['上杆腕铰链', '下杆加速', '短收送杆'],
  ),
  DrillDetail(
    drillId: 'drill_accelerate_through',
    name: '加速通过切杆',
    targetIssue: 'chipping_decel',
    description: '强调触球后杆头仍向目标加速，避免减速或挑球。',
    durationMinutes: 15,
    sets: 3,
    difficulty: '进阶',
    tips: ['减速击球常伴随挑球，先练低弹道滚进', '想象杆头要「穿过」球而非「舀」球'],
    steps: ['上杆至腰高以内', '触球后杆头向目标加速', '送杆时胸朝向目标'],
  ),
];

final Map<String, DrillDetail> _drillMap = {
  for (final d in _drills) d.drillId: d,
};

DrillDetail getDrillDetail(String drillId) {
  final found = _drillMap[drillId];
  if (found != null) return found;
  return DrillDetail(
    drillId: drillId,
    name: drillId,
    targetIssue: 'general',
    description: '教练推荐的针对性训练动作',
    durationMinutes: 15,
    sets: 3,
    difficulty: '入门',
    steps: const ['按照教练建议完成该动作', '每次 15 分钟，每周 3 次'],
  );
}
